#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

require_relative 'lib/config'
require_relative 'lib/slack_notifier'

config_file = File.join(File.dirname(__FILE__), 'config.json')
config = Config.new(JSON.parse(File.read(config_file)))

slack = SlackNotifier.new(config.slack_webhook_url)
slack.send('Hello World!')
