#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'lib/config'
require_relative 'lib/slack_notifier'

config_file = File.join(File.dirname(__FILE__), 'config.json')
config = Config.from_file(config_file)

slack = SlackNotifier.new(config.slack_webhook_url)
slack.send('Hello World!')
