#!/usr/bin/env ruby
# frozen_string_literal: true

require 'date'

require_relative 'lib/config'
require_relative 'lib/gitlab'
require_relative 'lib/slack_notifier'

config = Config.from_file(File.join(File.dirname(__FILE__), 'config.json'))
gitlab = Gitlab.new(config.gitlab_url, config.gitlab_token, config.gitlab_group_ids)
slack = SlackNotifier.new(config.slack_webhook_url)

message = "### Open Merge Requests - #{Date.today.strftime('%e %B')}\n" \
          "If you are still working on a merge request, mark it as WIP and it will not appear in the list.\n\n"

gitlab.open_merge_requests.each do |merge_request|
  if message.length > 3000
    slack.send(message)
    message = "*The list continues...*\n"
  end
  message += merge_request.to_markdown
end
slack.send(message)
